steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v3

 # Get flutter dependencies and Compile test case.
    - run: flutter pub get
  
  - name: Run Flutter Test
        run: flutter test
        
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
